"""empty message

Revision ID: 10aa64ec0724
Revises: 4969dd05b5a4
Create Date: 2016-12-04 17:23:53.234356

"""

# revision identifiers, used by Alembic.
revision = '10aa64ec0724'
down_revision = '4969dd05b5a4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ibati_advertisement', sa.Column('type', sa.String(length=50), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ibati_advertisement', 'type')
    ### end Alembic commands ###
